#!/usr/bin/ruby

#
# > Summary
# This file is aliased to /usr/local/bin/xiki, so it can be
# called from the command line.  It exposes xiki menus.
#
# > Example
# $ xiki ip
#   111.1.1.111
#
# To create the alias, see:
# @xiki/setup/install command/
#

require 'rubygems'

# Generate with correct path (see below)
xiki_dir = "/projects/xiki/"

require "#{xiki_dir}/ol"

$:.unshift xiki_dir.sub(/\/$/, '')
$:.unshift '/projects/xiki/etc/stubs/'

load "xiki_command.rb"
result = XikiCommand.run

exit 0

# TODO: Start with template, and when installing, change:
  # - #!.. line to: result of: `which ruby`
  # - xiki_dir to: Xiki.dir


